cp -r ~/.tmux.conf .
cp -r ~/.zshrc .
cp -r ~/.ideavimrc .
cp -r ~/.xbindkeysrc .
cp -r ~/.config/nvim ./.config
cp -r ~/.config/vifm ./.config
cp -r ~/.config/i3 ./.config
cp -r ~/.config/dunst ./.config
cp -r ~/.config/kitty ./.config
cp -r ~/.config/sway ./.config
